name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup the .NET Core environment
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.404

    # Install all the project dependencies
    - name: Install dependencies
      run: dotnet restore

    # Compile to a single .EXE [Windows]
    - name: Build for Windows
      run: dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true
      
      # Compile to a single .EXE [Linux]
    - name: Build for Linux
      run: dotnet publish -r linux-x64 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true
      
    # Test the build
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
    # Create a Release
    - name: Upload Automated Build
      id: upload-release-asset
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: automated-build
        name: Automated Build
        allowUpdates: true
        draft: false
        prerelease: true
        artifacts: "WSE Case Study/bin/Release/netcoreapp3.1/win-x64/publish/WSE Case Study.exe,WSE Case Study/bin/Release/netcoreapp3.1/linux-x64/publish/WSE Case Study"
        body: |
          Automated Build from latest commit using GitHub Actions!
          May or may not work as expected.
          
          **Build against:** ${{ github.sha }}
          Linux (64-bit): WSE.Case.Study
          Windows (64-bit): WSE.Case.Study.exe